site_name: "Fable（日本語訳）"
site_url: https://example.net/fable-ja/
site_author: Toshiki Hayashi

docs_dir: 'docs'
copyright: "Copyright &copy; 2022 Toshiki Hayashi"
repo_url: https://github.com/to884/fable-ja
repo_name: to884/fable-ja

theme:
  name: material                # Material for MkDocs
#  custom_dir: overrides         # カスタマイズ用ディレクトリ
  language: ja                  # 日本語検索: 有効
  icon:
    logo: fontawesome/solid/book
  font:
    text: Kosugi
#    text: Sawarabi Gothic
#    text: Yusei Magic
#    text: BIZ UDGothic
    code: Source Code Pro
  palette:
    - media: "(prefers-color-scheme: ligth)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: "ダークモードに切り替え"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: "ライトモードに切り替え"
  features:
    - tabs
    - content.code.annotate     # コード内注釈
    - content.tabs.link         # ページ内タブ連動： 有効
    - navigation.instant        # インスタントロード: 有効
#    - navigation.tabs           # 第一レベルのタブ化
    - navigation.section        # ナビゲーションセクション: 有効
#    - navigation.indexes        # 第1ページの概要化: 有効
    - navigation.top            # Back to Top の追加: 有効
#    - toc.integrate             # 目次の統合
    - toc.follow                # 目次の追従: 有効
plugins:
  - search:
      separator: '[\s\-\.]+'      # 単語のセパレーターをスペース、ハイフン、ドットに設定
  - git-revision-date-localized:  # Git との連携(日付など表示)
      type: timeago

markdown_extensions:
  - abbr                        # 略語
  - pymdownx.snippets           # スニペット(外部ファイル展開)
  - admonition                  # Note、注釈、警告などコラム
  - pymdownx.highlight:         # コードハイライト
      linenums: false           # 行番号: 無効
      linenums_style: table     # 行番号スタイル: テーブル
  - pymdownx.inlinehilite       # インラインコードブロック: 有効
  - pymdownx.keys               # キー用画像有効 例： ++ctrl+c++ 
  - pymdownx.superfences        # 他のブロック内のコードブロックのネスト: 有効
  - pymdownx.tabbed             # マークダウン内タブ: 有効
  - footnotes                   # 脚注
  - attr_list                   # リンク(画像、ボタンなど)の属性: 有効
  - pymdownx.arithmatex:        # MathJax: 有効
      generic: true
  - meta                        # マークダウン内メタ情報: 有効
  - toc:
      toc_depth: 4              # 目次の深さ: h2
      permalink: true           # パーマリンク: 有効
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
  - "stylesheets/theme.css"

nav:
  - "はじめに":
    - "Fable とは": "introduction/index.md"
    - ".NET 開発者ですか？": "introduction/dotnet-users-read-this.md"
    - "JS 開発者ですか？": "introduction/js-users-read-this.md"
  - "F# ははじめて？":
    - "言語を学ぶ": "new-to-fsharp/learning-the-language.md"
    - "let キーワード": "new-to-fsharp/let-keyword.md"
  - "2 ステップでできる Fable":
    - "セットアップ": "2-steps/setup.md"
    - "新しいプロジェクトを開始する": "2-steps/your-first-fable-project.md"
  - "あなたの Fable プロジェクト":
    - "プロジェクトファイル": "your-fable-project/project-file.md"
    - "Fable ライブラリを使おう": "your-fable-project/use-a-fable-library.md"
    - "Fable ライブラリを作ろう": "your-fable-project/author-a-fable-library.md"
    - "ビルドと実行": "your-fable-project/build-and-run.md"
    - "テスト": "your-fable-project/testing.md"
  - "JavaScript とコミュニケーションする":
    - "Fable から JS を呼び出す": "communicate/js-from-fable.md"
    - "JavaScript から Fable を呼び出す": "communicate/fable-from.js.md"
  - ".NET から Fable へ":
    - ".NET と F# の互換性": "dotnet/compatibility.md"
    - "数値型": "dotnet/numbers.md"
  - "その他":
    - "公式サンプルをチェック": "miscellaneous/official-samples.md"
    - "動画で見る Fable": "miscellaneous/fable-in-video.md"